services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: volleyvision
      POSTGRES_USER: volleyvision_user
      POSTGRES_PASSWORD: volleyvision_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U volleyvision_user -d volleyvision"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://volleyvision_user:volleyvision_password@db:5432/volleyvision

volumes:
  postgres_data: